### ISSUE TITLE
panic: interface conversion: interface {} is nil, not map[string]interface {}

### ISSUE THREAD

**Issue by zainul** [dimaskiddo/go-whatsapp-rest#54] opened 2021-12-24 06:09 UTC
got panic after scanning the barcode
```go
wac.SetClientVersion(2,2147,16)
```
panic code snippet
```go
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 14 [running]:
github.com/Rhymen/go-whatsapp.newInfoFromReq(0xc000098990, 0x38)
	/home/x/play/src/github.com/zainul/kasir/vendor/github.com/Rhymen/go-whatsapp/session.go:63 +0xc5e
github.com/Rhymen/go-whatsapp.(*Conn).Login(0xc000152f00, 0xc0000b23c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/x/play/src/github.com/zainul/kasir/vendor/github.com/Rhymen/go-whatsapp/session.go:268 +0x1002

```

**Comment by dimaskiddo** [comment] 2022-01-06 10:18
Hai @zainul thank's for the report will try to reproduce the issue. This issue may lead to need an upgrade of Rhymen/go-whatsapp library version

**Comment by dimaskiddo** [comment] 2022-01-06 10:30
Hai @zainul i just test with no changes except the WhatsApp Client Version is Upgraded and it work fine, can you mak sure that your connection is stable, some issues are related to the connection

![image](https://user-images.githubusercontent.com/21129987/148368898-673418fd-6323-4e23-8e82-9cef8acc924b.png)
![image](https://user-images.githubusercontent.com/21129987/148369037-26d01e2a-59c1-4a7e-ac7f-eb868ab0b01f.png)

**Comment by dimaskiddo** [comment] 2022-01-10 07:11
Closing this issue due to maybe this more related to main library Rhymen/go-whatsapp and cannot reproduce in current state of this repository. Feel free to re-open

**Closed by dimaskiddo** 2022-01-10 07:11 UTC
