### ISSUE TITLE
Error in Sending Message 

### ISSUE THREAD

**Issue by breadpanz** [dimaskiddo/go-whatsapp-rest#3] opened 2019-04-12 10:09 UTC
`error processing data: received invalid data`

The error above shows whenever I tried to send a message though, It's successful

**Comment by dimaskiddo** [comment] 2019-04-12 20:35
Yups i think this is caused by not filtering a message that come from the current JID it's self, make sure to not read your own message in handler, and i still bypass this error in go-whatsapp-cli since it has a test mode, that make only listen and read from the same JID

May be you can try the echo example in go-whatsapp package, since this error message is related with the go-whatsapp handler

**Comment by breadpanz** [comment] 2019-04-13 04:19
Opps. I see. Thanks mate! The error message came from the go-whatsapp handler itself.

link with this issue: https://github.com/Rhymen/go-whatsapp/issues/125

**Comment by dimaskiddo** [comment] 2019-04-13 05:50
I have used the stable commit version from Rhymen/go-whatsapp, and i think the issues still there or may be as i said before it's caused by the handler reading it's own sended data, since it's handling data reading from whatsapp server, you can check it in read.go file

So, can i close this issue or leave this as reference to Rhymen/go-whatsapp?
I think SchulteMK will try to fix or investigate this, since he refactor the readPump

**Closed** 2019-04-22 05:54 UTC
